// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVhwZVfHehnKv4i6VAqh7jeEZlwe4i2Ys',
    appId: '1:460026618055:web:7577dfa7626dea618f9ee2',
    messagingSenderId: '460026618055',
    projectId: 'usuarios-cd0f3',
    authDomain: 'usuarios-cd0f3.firebaseapp.com',
    storageBucket: 'usuarios-cd0f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCml3dEJT_ClQZRegZUKlB1DhYfxUkH_ws',
    appId: '1:460026618055:android:5253ab2c5b57119f8f9ee2',
    messagingSenderId: '460026618055',
    projectId: 'usuarios-cd0f3',
    storageBucket: 'usuarios-cd0f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq914BB8gFx6Gv0nuv54donHMhcPh8qf4',
    appId: '1:460026618055:ios:a4b8c217cde801778f9ee2',
    messagingSenderId: '460026618055',
    projectId: 'usuarios-cd0f3',
    storageBucket: 'usuarios-cd0f3.firebasestorage.app',
    iosBundleId: 'com.example.autenticacioExemple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq914BB8gFx6Gv0nuv54donHMhcPh8qf4',
    appId: '1:460026618055:ios:a4b8c217cde801778f9ee2',
    messagingSenderId: '460026618055',
    projectId: 'usuarios-cd0f3',
    storageBucket: 'usuarios-cd0f3.firebasestorage.app',
    iosBundleId: 'com.example.autenticacioExemple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVhwZVfHehnKv4i6VAqh7jeEZlwe4i2Ys',
    appId: '1:460026618055:web:8c6508488a8bff668f9ee2',
    messagingSenderId: '460026618055',
    projectId: 'usuarios-cd0f3',
    authDomain: 'usuarios-cd0f3.firebaseapp.com',
    storageBucket: 'usuarios-cd0f3.firebasestorage.app',
  );
}
