// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC95hgCk5TMR9xdeLzfysQ2sVMzaflENTg',
    appId: '1:572195930055:web:62fb63827c142555f523e2',
    messagingSenderId: '572195930055',
    projectId: 'todolist-flutter-fb035',
    authDomain: 'todolist-flutter-fb035.firebaseapp.com',
    storageBucket: 'todolist-flutter-fb035.firebasestorage.app',
    measurementId: 'G-3989LG19HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxtCy27_QANCll85QGVPtaKQ9uwa-RkWI',
    appId: '1:572195930055:android:ae289af1fc98440bf523e2',
    messagingSenderId: '572195930055',
    projectId: 'todolist-flutter-fb035',
    storageBucket: 'todolist-flutter-fb035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC1beILzf3ppQPMTHlJf9VSkwKJEriTmw',
    appId: '1:572195930055:ios:c95f8aeb71b70a65f523e2',
    messagingSenderId: '572195930055',
    projectId: 'todolist-flutter-fb035',
    storageBucket: 'todolist-flutter-fb035.firebasestorage.app',
    iosClientId: '572195930055-74f4p5gbaj4qmaa4snot0uv3j8218pu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.autenticacioExemple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC1beILzf3ppQPMTHlJf9VSkwKJEriTmw',
    appId: '1:572195930055:ios:c95f8aeb71b70a65f523e2',
    messagingSenderId: '572195930055',
    projectId: 'todolist-flutter-fb035',
    storageBucket: 'todolist-flutter-fb035.firebasestorage.app',
    iosClientId: '572195930055-74f4p5gbaj4qmaa4snot0uv3j8218pu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.autenticacioExemple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC95hgCk5TMR9xdeLzfysQ2sVMzaflENTg',
    appId: '1:572195930055:web:aa069d754f264db2f523e2',
    messagingSenderId: '572195930055',
    projectId: 'todolist-flutter-fb035',
    authDomain: 'todolist-flutter-fb035.firebaseapp.com',
    storageBucket: 'todolist-flutter-fb035.firebasestorage.app',
    measurementId: 'G-JSX23GYYM1',
  );

}